# Generated by Django 5.1.5 on 2025-09-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentacion_auditores', '0016_alter_actaauditoria_aspectos_relevantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('checkpoint_iaf_md4', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumple', models.BooleanField(default=False)),
                ('no_cumple', models.BooleanField(default=False)),
                ('no_aplica', models.BooleanField(default=False)),
                ('aspecto_mejora', models.BooleanField(default=False)),
                ('concepto_mejora', models.TextField(blank=True, null=True)),
                ('concepto_no_conformidad', models.TextField(blank=True, null=True)),
                ('evidencia', models.CharField(blank=True, choices=[('documental', 'Evidencia Documental'), ('fotografica', 'Evidencia Fotográfica'), ('audiovisual', 'Evidencia Audiovisual'), ('documental_fotografica', 'Evidencia Documental y Fotográfica'), ('documental_audiovisual', 'Evidencia Documental y Audiovisual'), ('fotografica_audiovisual', 'Evidencia Fotográfica y Audiovisual'), ('documental_fotografica_audiovisual', 'Evidencia Documental, Fotográfica y Audiovisual')], default='documental', max_length=100, null=True)),
                ('concepto_evidencia', models.TextField(blank=True, null=True)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('subsanado', models.BooleanField(default=False)),
                ('como_se_subsano', models.TextField(blank=True, null=True, verbose_name='¿Cómo se subsanó la no conformidad?')),
                ('acta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentacion_auditores.actaauditoria')),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejecucion_auditoria.requisitoauditoria')),
            ],
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsanado', models.BooleanField(default=False)),
                ('comentario_subsanacion', models.TextField(blank=True, null=True)),
                ('fecha_subsanacion', models.DateField(blank=True, null=True)),
                ('ejecucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ejecucion_auditoria.ejecucionrequisito')),
            ],
        ),
    ]
