# Generated by Django 5.1.5 on 2025-09-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion_auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionrequisito',
            name='evidencia',
            field=models.CharField(blank=True, choices=[('documental', 'Evidencia Documental'), ('fotografica', 'Evidencia Fotográfica'), ('audiovisual', 'Evidencia Audiovisual'), ('documental_fotografica', 'Evidencia Documental y Fotográfica'), ('documental_audiovisual', 'Evidencia Documental y Audiovisual'), ('fotografica_audiovisual', 'Evidencia Fotográfica y Audiovisual'), ('documental_fotografica_audiovisual', 'Evidencia Documental, Fotográfica y Audiovisual')], max_length=100, null=True),
        ),
    ]
