# Generated by Django 5.1.5 on 2025-09-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0014_actaauditoria_muestra_normal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horaactividadplan',
            options={'ordering': ['fecha', 'hora'], 'verbose_name': 'Actividad del Plan', 'verbose_name_plural': 'Actividades del Plan'},
        ),
        migrations.AddField(
            model_name='horaactividadplan',
            name='cargo_auditado',
            field=models.CharField(blank=True, help_text='Cargo del entrevistado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='horaactividadplan',
            name='nombre_auditado',
            field=models.CharField(blank=True, help_text='Nombre de la persona entrevistada', max_length=255, null=True),
        ),
    ]
