# Generated by Django 5.1.5 on 2025-09-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0015_alter_horaactividadplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaauditoria',
            name='aspectos_relevantes',
            field=models.TextField(blank=True, null=True, verbose_name='Aspectos relevantes del servicio auditado'),
        ),
    ]
