# Generated by Django 5.1.5 on 2025-09-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0016_alter_actaauditoria_aspectos_relevantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaauditoria',
            name='conclusiones_etapa1',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusiones de etapa 1'),
        ),
        migrations.AddField(
            model_name='actaauditoria',
            name='conclusiones_etapa2',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusiones de etapa 2'),
        ),
        migrations.AddField(
            model_name='actaauditoria',
            name='quejas_registradas',
            field=models.TextField(blank=True, null=True, verbose_name='Quejas registradas'),
        ),
    ]
