# Generated by Django 5.1.5 on 2025-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_ente_certificador',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Organismo_certificador_y_alcance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
