# Generated by Django 5.1.5 on 2025-10-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_remove_cliente_nombre_ente_certificador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_establecimiento',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_propietario',
            field=models.CharField(max_length=125),
        ),
    ]
